swagger: '2.0'
info:
  description: El servicio de inteligencia rebelde ha detectado un llamado de auxilio de una nave portacarga imperial a la deriva en un campo de asteroides. Este programa debe retornar la fuente y contenido del mensaje de auxilio. Para esto, cuenta con tres satélites que te permitirán triangular la posición, ¡pero cuidado! el mensaje puede no llegar completo a cada satélite debido al campo de asteroides frente a la nave.
  version: 0.0.1
  title: quasarfire
basePath: /
paths:
  '/topsecret_split/{satellite_name}':
    post:
      tags:
        - topsecret
      summary: Recieves satellite stolen information
      description: Recieves satellite stolen information
      operationId: topsecretSplit
      parameters:
        - name: satellite_name
          in: path
          description: name of satellite
          required: true
          type: string
        - name: body
          in: body
          description: Stolen information from target
          required: true
          schema:
            $ref: '#/definitions/StolenMessage'
      responses:
        '200':
          description: successful operation
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '400':
          $ref: '#/responses/400'
        '500':
          $ref: '#/responses/500'
  '/topsecret_split/':
    get:
      tags:
        - topsecret
      summary: Provides the reconstructed message and target location
      description: Provides the reconstructed message and target location
      operationId: topsecret
      produces:
        - application/json
      responses:
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '404':
          $ref: '#/responses/404'
        '500':
          $ref: '#/responses/500'
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/OriginalMessage'
  '/satellite_fleet/':
    post:
      tags:
        - topsecret
      summary: Recieves satellite list
      description: Recieves satellite list
      operationId: setFleet
      parameters:
        - name: body
          in: body
          description: Stolen information from target
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Satellite'
      responses:
        '200':
          description: successful operation
        '401':
          $ref: '#/responses/401'
        '403':
          $ref: '#/responses/403'
        '400':
          $ref: '#/responses/400'
        '500':
          $ref: '#/responses/500'
definitions:
  StolenMessage:
    type: object
    required:
      - distance
      - name
      - message
    properties:
      distance:
        type: number
        format: float
        example: 1
      name:
        type: string
        example: Kenobi
      message:
        type: array
        items:
          type: string
          example: parcial
  Satellite:
    type: object
    required:
      - position
      - name
    properties:
      position:
        type: object
        allOf:
          - $ref: '#/definitions/Point2D'
      name:
        type: string
        example: Kenobi
  OriginalMessage:
    type: object
    required:
      - position
      - message
    properties:
      position:
        type: object
        allOf:
          - $ref: '#/definitions/Point2D'
      message:
        type: string
        example: Este es un mensaje
  Point2D:
    type: object
    required:
      - x
      - y
    properties:
      x:
        type: number
        format: float
        example: 1
      y:
        type: number
        format: float
        example: 1
responses:
  '401':
    description: Unauthorized
  '403':
    description: Forbidden
  '404':
    description: Element not found
  '400':
    description: Bad request
  '500':
    description: Internal server error